#   █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
#  ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
#  ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
#  ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
#  ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
#  ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝

general.import = ["~/.config/alacritty/colors.toml", "~/.config/alacritty/fonts.toml"]

general.live_config_reload = true

[cursor]
blink_interval = 550
unfocused_hollow = false
thickness = 0.15

[cursor.style]
blinking = "Always"
shape = "Block"

[selection]
save_to_clipboard = true

[window]
decorations = "none"
dynamic_title = true
opacity = 1.0
dynamic_padding = false

[window.padding]
x = 4
y = 4

[scrolling]
history = 10000
multiplier = 3

[bell]
animation = "Linear"
duration = 0
command = { program = "paplay", args = ["/usr/share/sounds/freedesktop/stereo/dialog-error.oga"] }
